#
# This file is automatically generated. Do not manually edit this file.
#
{% if helpers.exists('OPNsense.Cloudflared.general.enabled') and OPNsense.Cloudflared.general.enabled == '1' %}
cloudflared_enable="YES"
{% else %}
cloudflared_enable="NO"
{% endif %}
cloudflared_token_file="/usr/local/etc/cloudflared/token"
{% if helpers.exists('OPNsense.Cloudflared.general.no_autoupdate') and OPNsense.Cloudflared.general.no_autoupdate == '1' %}
cloudflared_no_autoupdate="YES"
{% else %}
cloudflared_no_autoupdate="NO"
{% endif %}
{% if helpers.exists('OPNsense.Cloudflared.general.post_quantum') and OPNsense.Cloudflared.general.post_quantum == '1' %}
cloudflared_post_quantum="YES"
{% else %}
cloudflared_post_quantum="NO"
{% endif %}
{% if helpers.exists('OPNsense.Cloudflared.general.quic_disable_pmtu_discovery') and OPNsense.Cloudflared.general.quic_disable_pmtu_discovery == '1' %}
cloudflared_quic_disable_pmtu_discovery="YES"
{% else %}
cloudflared_quic_disable_pmtu_discovery="NO"
{% endif %}
