[start]
command:/usr/local/sbin/configctl service cloudflared start
parameters:
type:script
message:Starting Cloudflare Tunnel

[stop]
command:/usr/local/sbin/configctl service cloudflared stop
parameters:
type:script
message:Stopping Cloudflare Tunnel

[restart]
command:/usr/local/sbin/configctl service cloudflared restart
parameters:
type:script
message:Restarting Cloudflare Tunnel

[status]
command:/usr/local/sbin/configctl service cloudflared status
parameters:
type:script
message:Cloudflare Tunnel Status

[reconfigure]
command:/usr/local/opnsense/scripts/OPNsense/Cloudflared/reconfigure.sh
parameters:
type:script
message:Reconfiguring Cloudflare Tunnel

[install_binary]
command:/usr/local/opnsense/scripts/OPNsense/Cloudflared/install_binary.sh
parameters:
type:script
message:Installing Cloudflare Tunnel binary
